apiVersion: v1
kind: Service
metadata:
  name: ping-pong-app
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 3000
  selector:
    app: ping-pong-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      containers:
      - name: ping-pong-app
        image: aliyahnaini/pingpongapp:latest
        ports:
        - containerPort: 3000
